---
- hosts: all
  remote_user: root

  vars:
    # Username
    user: olivier
    # Timezone
    timezone: 'Europe/Paris'
    # SSH
    common_ssh_port: 2222

  tasks:
  
    ###################
    # Sudo Management
    ###################
    - name: Install sudo
      apt: pkg=sudo state=installed update_cache=yes cache_valid_time=3600
      when: ansible_os_family == "Debian"
      
    - name: Create sudoers.d directory
      file:
        path: /etc/sudoers.d
        owner: root
        group: root
        mode: 0755
        state: directory

    - name: Set includedir in sudoers
      lineinfile:
        dest: /etc/sudoers
        line: "#includedir /etc/sudoers.d"
        state: present
        validate: "/usr/sbin/visudo -cf %s"

        
    ###################
    # User Management
    ###################
    - name: Create user {{ user }}
      user: name={{ user }}
            comment="{{ user }} user"
            shell=/bin/bash

    - name: Add {{ user }} to sudoers     
      lineinfile: dest=/etc/sudoers.d/{{ user }}-sudoer
                  regexp="{{ user }} ALL"
                  line="{{ user }} ALL=(ALL) ALL"
                  state=present
                  create=True
                  validate='visudo -cf %s'                  

    - name: Add my public key to {{ user }}
      authorized_key: user={{ user }}
                      key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    
    
    ###################
    # Required. tools
    ###################
    - name: Install usefull system tools
      apt: name={{ item }} state=present
      with_items:
        - ufw
        - unattended-upgrades
        
        
    ###################
    # Packages Management
    ###################                
    - name: Update APT package cache
      apt: update_cache=yes cache_valid_time=3600
  
    - name: Upgrade APT to the latest packages
      apt: upgrade=safe
      
    - name: Adjust APT update intervals
      copy: src=apt_periodic dest=/etc/apt/apt.conf.d/10periodic

      
    ###################
    # Time management
    ###################
    - name: Set local timezone
      copy: content={{ timezone }}
            dest=/etc/timezone
      notify: update tzdata

    - name: Install NTP (and update apt cache for the first install)
      apt: name=ntp state=present
           update_cache=yes

    - name: Start the ntp service
      service: name=ntp state=started enabled=true

      
    ###################
    # Security
    ###################
    - name: Install fail2ban
      apt: name=fail2ban state=present

    - name: Start fail2ban service
      service: name=fail2ban state=started enabled=true

    - name: Setup ufw
      ufw: state=enabled policy=deny

    - name: Allow ssh traffic
      ufw: rule=allow port={{ common_ssh_port }} proto=tcp
            
    - name: Disallow password authentication
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PasswordAuthentication"
                  line="PasswordAuthentication no"
                  state=present
      notify: Restart ssh

    - name: Change ssh port
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^Port"
                  line="Port {{common_ssh_port }}"
                  state=present
      notify: Restart ssh

  ###################
  # Handlers
  ###################
  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted
    - name: update tzdata
      command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata
